### ISSUE TITLE
Restrictions working/not working in 3.6.10

### ISSUE THREAD

**Issue by Droidphilev** [M66B/XPrivacy#2195] opened 2015-05-23 08:48 UTC
Seems to work:

Device ID
Accounts

Seems not working:

IMEI
Sim subscriber ID
Sim serial
Wifi MAC
Provider name
GSF

When opening the app "Phone Info Samsung" i get following error:

An error has occured in sub: java.io.FileNotFoundException: XPrivacy

**Comment by M66B** [comment] 2015-05-23 08:57
*java.io.FileNotFoundException: XPrivacy* is caused by a restriction and is not a bug.

**Comment by M66B** [comment] 2015-05-23 10:01
@dk-zero-cool I have already checked if XTelephonyManager hooks are placed and they are, but maybe it should be done at another place, for example if the telephony manager doesn't run with Android anymore, but in a separate process.

XWifiManager/server hooks are not placed and I couldn't figure out yet where that should be done (it doesn't work when restricting Android: class not found).

**Comment by M66B** [comment] 2015-05-23 12:35
Will be fixed in the next release (soon).

**Closed by M66B** 2015-05-23 12:35 UTC
Labels: bug, Lollipop
