### ISSUE TITLE
Bug: Hard crash using XPrivacy with Voxer app

### ISSUE THREAD

**Issue by Gitoffthelawn** [M66B/XPrivacy#2287] opened 2015-10-21 23:24 UTC
**Steps Taken:**
1. Created XPrivacy default template that sets *On Demand* (with default *restrict*) for NetworkInfo.isConnected (category: Internet).
2. Installed [Voxer app](https://play.google.com/store/apps/details?id=com.rebelvox.voxer).
3. Allowed Voxer access to internet via Firewall.
4. Ran Voxer.

**Observed Behavior:**
1. Voxer loaded.
2. XPrivacy displayed its *On Demand* window for NetworkInfo.isConnected.  The default action was Deny, as expected.
3. XPrivacy *On Demand* window totally nonresponsive.  The XPrivacy buttons 'Allow', 'Deny', 'I don't know', and 'Reset', as well as all of the checkboxes, do not respond.
4. XPrivacy *On Demand* window times out and then reloads itself.
5. Number 4 repeats approx 3 times.
6. The test device hard crashes and turns off.
7. The device can be started again using the hardware power button.
8. Upon reboot, the process starts again at Step 2 and repeats through Step 6.

**Expected Behavior:**
1. XPrivacy *On Demand* window responding to user input.

**Test System:**
1. Test Device XPrivacy Version: PRO 3.6.19 (481).  Running in compatibility mode.
2. Test Device Xposed Version: 2.6.1
3. Test Device OS Version: Android 4.4.2 (LGE).

**Comment by M66B** [comment] 2015-10-22 05:24
The problem with the on demand dialog is being described in the limitations section. The crash is probably caused by the restrictions, but only a logcat can reveal the real cause.

**Comment by Gitoffthelawn** [comment] 2015-10-22 06:31
Due to the hard crash, what can capture the logcat?  It will need to flush the write cache after each logcat line.

**Comment by M66B** [comment] 2015-10-22 06:32
If you capture the logcat in real-time from a connected PC, you will able to catch the details of the crash.

**Comment by M66B** [comment] 2015-10-22 06:34
Note that I estimate the chance that this is caused by a bug in XPrivacy to be a low chance.
Therefore I will close this issue, but I will look into a logcat when provided (you can still comment, even if the issue is closed).

**Closed by M66B** 2015-10-22 06:34 UTC
Labels: question

**Comment by Gitoffthelawn** [comment] 2015-10-22 22:54
Sounds good.  If the crash is most likely caused by the restriction, it may not be worth our time to pursue a logcat.

When XPrivacy restricts NetworkInfo.isConnected, what data is provided to the restricted app?
