### ISSUE TITLE
[Req] edit whitelist/blacklist: wildcards & URL path

### ISSUE THREAD

**Issue by DefyMiners** [M66B/XPrivacy#2103] opened 2015-01-01 07:16 UTC
A particular set of apps wish to load

sub.domain.tld/PathChaotic7ehd8wjd72b-73udhe/morechaos 

Please allow wildcard matching in path. The app in mind does use less than a dozen

Sub1.them.tld 
Sub2.them.tld

Not numbered literally.

Whereas some apps offer host wildcard sub prefixing such as

*.facebook.*:* 

Perhaps how the fqdn load is attempted? Webview vs otherly? 

Hope to use whitelist view where no enable|disable is the only exit, to long click entry for text edit.

**Comment by DefyMiners** [comment] 2015-01-01 07:18
^ where no == where now 

Using HOSTS blocking for these cases is suboptimal.

**Comment by DefyMiners** [comment] 2015-01-01 07:20
only exit == only toggle 

[[Yikes]]

**Comment by M66B** [comment] 2015-01-01 07:30
There are already enough options in the on demand restricting dialog, which cannot be shown for too long, else Android will crash, and I don't want to add anymore, sorry.

**Comment by DefyMiners** [comment] 2015-01-01 09:37
Oh I do not want them in that short lived ui, but only in the whitelist view ui.

**Comment by DefyMiners** [comment] 2015-01-01 09:38
"Manage Whitelists"

That dialog.

**Comment by M66B** [comment] 2015-01-01 09:39
I don't want an edit function in the white/black list view, because it will result in mistakes and therefore in too many support questions.

**Comment by M66B** [comment] 2015-01-01 09:46
I will leave this issue open and see if I can come up with an idea how to handle this, since it is often asked for.

**Comment by banderos101** [comment] 2015-01-14 19:00
Thankyou marcel,  even if your not able to find a solution thanks for looking into this further, goodluck

**Comment by M66B** [comment] 2015-01-21 13:18
Duplicate of #2056

**Closed by M66B** 2015-01-21 13:18 UTC
Labels: enhancement
