### ISSUE TITLE
Lollipop: Prevents Xposed Framework from starting when enabled

### ISSUE THREAD

**Issue by tomtiger11** [M66B/XPrivacy#2144] opened 2015-02-17 13:47 UTC
XPrivacy stops the Zygote service from running properly when enabled. This does not happen when another app, such as Amplify, is enabled.

Logcat when Amplify is enabled: https://gist.githubusercontent.com/tomtiger11/12e15f4ae9a7d048b4d7/raw/gistfile1.txt

Logcat when XPrivacy is enabled: https://gist.githubusercontent.com/tomtiger11/5db9b4a145ad8ba1a1c7/raw/gistfile1.txt

XPrivacy 3.6.6

**Comment by M66B** [comment] 2015-02-17 14:05
I don't think this is directly caused by XPrivacy, so I will close this issue for now.

F/libc ( 5441): Fatal signal 13 (SIGPIPE), code 0 in tid 5441 (tmp-mksh)

**Closed** 2015-02-17 14:05 UTC
Labels: question

**Comment by tomtiger11** [comment] 2015-02-17 18:01
Was an issue with the ROM, however restricting shell doesn't work for many apps. May well just be a limitation of the app.
