### ISSUE TITLE
Restrict while visible

### ISSUE THREAD

**Issue by NaabKing** [M66B/XPrivacy#2125] opened 2015-01-28 03:22 UTC
I was using my GF-s iPhone for a little and came across an interesting feature (that is build in), but on iPhone you can set permissions for a program to "Allow", "Don't Allow" and "Allow when using", the last feature i think is really great and i think it would be very good to replace "Ask me every time" and i can explain why.

For example, if i run "Google Maps" and i check "Ask me every time", it will ask me 20 times per minute to click on "Allow", so basically you just need to "Don't ask me again" and "Allow", which means it has permanent "Allow", the "Allow when runing" feature would eliminate that and would allow the Google Maps to get my location ONLY when i have it open and runing (and not in the background when i don't know?).

This was just an example, this could apply to SO many programs and i think it would be great.

Another good example would be "Camera", i want my "Camera app" to use Camera permission only when i have clicked on it (cuz obviously, i wanna tae a picture), but i don't want it to take pictures (of me) when i unlock the phone for example, i'm not saying it's doing that, but you never know (*khm* NSA *khm*), i think in that case, "allow when runing" is much better choice then "allow for 5 minutes".

**Comment by M66B** [comment] 2015-01-28 08:02
http://forum.xda-developers.com/showpost.php?p=58473863&postcount=13565

**Comment by Magissia** [comment] 2015-01-28 14:34
I agree with the fact it will cause data leaks

----- Reply message -----
De : "Marcel Bokhorst" <notifications@github.com>
Pour : "M66B/XPrivacy" <XPrivacy@noreply.github.com>
Objet : [XPrivacy] [Feature request] "Allow when runing" permissions. (#2125)
Date : mer., janv. 28, 2015 09:02


http://forum.xda-developers.com/showpost.php?p=58473863&postcount=13565

---

**Comment by NaabKing** [comment] 2015-01-28 18:54
> I was thinking to allow/deny as long as the application is in the foreground/visible.

Thist is what i was asking for actually :D Allow a program to use a permission as long as it is in the "foreground/visible" (=

**Comment by kaizokan** [comment] 2015-01-30 19:42
Data leaks will also happen when these permissions are allowed permanently when people find it irritating to allow every time and thus allow permanently if needed for functionality. Changing the "allow once 'x' seconds" duration changes the default 30 seconds into the desired one, but that is not limited to the app in question, it changes also the default 30 seconds for the next/other popups/apps. Meaning that every time when not using the app in question the new x seconds needs to be changed back to 30 or whatever low value someone might prefer as default. This constantly changing the x seconds might be the cause for some people not making use of this functionality often (like me). 

I don't know how many people actually use or not use this functionality often. Just changing the behaviour of the x seconds on the next popup to the default one might already improve the usage. But if possible and if you, Marcel want to then i don't object for having the allow when visible function which of course is much better ;) 

A few apps (examples) where this will be useful are: 
TrackID (ALSO asking for Audio.startRecording when leaving/closing the app), 
Shazam (same as TrackID, might actually record all to also recognise tv programs in background)
"automatically identify songs, TV shows, and advertisements without having to reach for their phones" (2013)
Navigation apps. RouteRadar or Speed Cameras by Sygic keep listening to location in background.

**Comment by Magissia** [comment] 2015-01-30 23:27
Privacy is not a game, it's a life style, if you want to drop weapons and let them invade your data that's up to you, but don't force it to others.

----- Reply message -----
De : "kaizokan" <notifications@github.com>
Pour : "M66B/XPrivacy" <XPrivacy@noreply.github.com>
Cc : "Magissia" <nolododo@hotmail.com>
Objet : [XPrivacy] [Feature request] "Allow when runing" permissions. (#2125)
Date : ven., janv. 30, 2015 20:42


Data leaks will also happen when these permissions are allowed permanently when people find it irritating to allow every time and thus allow permanently if needed for functionality. Changing the "allow once 'x' seconds" duration changes the default 30 seconds into the desired one, but that is not limited to the app in question, it changes also the default 30 seconds for the next/other popups/apps. Meaning that every time when not using the app in question the new x seconds needs to be changed back to 30 or whatever low value someone might prefer as default. This constantly changing the x seconds might be the cause for some people not making use of this functionality often (like me).

I don't know how many people actually use or not use this functionality often. Just changing the behaviour of the x seconds on the next popup to the default one might already improve the usage. But if possible and if you, Marcel want to then i don't object for having the allow when visible function which of course is much better ;)

A few apps (examples) where this will be useful are:
TrackID (ALSO asking for Audio.startRecording when leaving/closing the app),
Shazam (same as TrackID, might actually record all to also recognise tv programs in background)
"automatically identify songs, TV shows, and advertisements without having to reach for their phones" (2013)
Navigation apps. RouteRadar or Speed Cameras by Sygic keep listening to location in background.


---

**Comment by kaizokan** [comment] 2015-01-31 10:27
I think you have misunderstood what i said. I agree that it can cause data leaks when allowing apps in the background. I was talking about an options (not forcing) for allowing apps that are 'visible', not in the background but visible on the screen. And before that i was talking about how 'others' might have there data invaded just because they get irritated by the current way it works and decide to allow permissions permanently.

**Comment by Magissia** [comment] 2015-02-01 09:50
An application can force itself on top with a one pixel transparent window without you ever noticing it. If you feel an application can access the data, leave it allowed, it's not useful to allow data lakes only when you use the software, if you feel this is a privacy issue, deny, if it's not, allow, that's all, there's no point to sometime allow data leaks... 


-------- Message d'origine --------
De : kaizokan <notifications@github.com>
Envoyé: 31 janvier 2015 11:27:41 CET
À : M66B/XPrivacy <XPrivacy@noreply.github.com>
Cc : Magissia <nolododo@hotmail.com>
Objet : Re: [XPrivacy] [Feature request] "Allow when runing" permissions. (#2125)

I think you have misunderstood what i said. I agree that it can cause data leaks when allowing apps in the background. I was talking about an options (not forcing) for allowing apps that are 'visible', not in the background but visible on the screen. And before that i was talking about how 'others' might have there data invaded just because they get irritated by the current way it works and decide to allow permissions permanently.

---

**Comment by kaizokan** [comment] 2015-02-01 14:30
There is/was a point in allowing when using, but according to what you said it won't work like intended since apps can force itself to the foreground and thus leak data. Good that you mentioned that. I almost thought you were saying something like "if you care about your privacy don't use android at all" ;)

**Comment by Cerberus-tm** [comment] 2015-02-01 22:12
This would be my #1 feature requestion, it is perhaps the most important thing that is still missing from Xprivacy. It would greatly enhance my privacy to block location for all Google applications in the background. I am very glad to hear that Marcel is perhaps even considering this.

What Magissia says it is true, and we shouldn't get a false sense of security from this. However, in many cases the choice is not between "allow on demand" or "allow when running": in that situation, "allow when in the foreground" is indeed slightly less safe; but in many cases the real choice is between "allow always" and "allow when in the foreground", because we find "on demand" too cumbersome for things you need to do often, such as location in Google Maps. Then we gain a lot of privacy, when we switch from "allow always" to "allow when in the foreground". As Kaizokan says, it is up to the user not to use this function if she doesn't trust it, like Magissia. It would be Apple-like to forbid other people from using it because it might be "confusing"!

The risk of self-activating applications with a transparent overlay can be mitigated in other ways. For one thing, we can use the existing function in Xprivacy to restrict overlays for an application. Secondly, we can use Greenify to ensure that applications cannot become active when we have not opened them.

Lastly, this might be a lot of work to implement, and perhaps a Tasker plugin would be more effective anyway. My main reason for saying this is that I would want to allow location etc. for Google services while some *other* application is active, like my train application: the Google location services, which use Wifi and Google's database to determine your location when GPS is not available, are highly useful for all other applications that use your location. It would be more complicated to implement this through Xprivacy. Unless perhaps there would be a special built-in thingy for Google's location services, just as there already is a special function for Google location that you can restrict under the category Location.

**Comment by kbtomo** [comment] 2015-02-08 11:56
How i can resolve my Samsung SM-N9006 mobile phone from installing ROM
MANANGER by JRimmy and i accedentaly edit the Customise Build Verno
setting in wrong procedure and aslo in Reboot Setting i accidentaly
set in Reboot Start UI, after  all i click the command reboot in my
mobile phone, and rebooting was done my mobile phone is Stock in
Mobile System Restarting and i try to Backup User Data and Restore
User Data in my phone System Recovery but its still not working?

**Comment by kbtomo** [comment] 2015-02-08 17:54
How i can fix or repair my Samsung SM-N9006 CSC:N9006CHUFNJ3
MODEM:N9006ZNUFNJ5  mobile phone from installing ROM MANANGER by JRummy and
i accedentaly edit the Customise Build Verno setting in wrong procedure and
aslo in Reboot Setting i accidentaly set in Reboot Start UI, after all i
click the command reboot in my mobile phone, and rebooting was done my
mobile phone is Stock in Mobile System Restarting and i try to Backup User
Data and Restore User Data in my phone System Recovery but its still not
working?

**Comment by M66B** [comment] 2015-02-08 17:55
@kbtomo please don't post random problems in unrelated issues.
@kbtomo how is this related to XPrivacy?

**Comment by M66B** [comment] 2015-02-11 18:25
I have attempted to implement this, but it appears this will not be very useful, because a lot of restrictions are evaluated before an application becomes visible (and even before an application is started). IMHO this would be a quite confusing and an unreliable feature, so I will not further pursue this.

**Closed by M66B** 2015-02-11 18:25 UTC
Labels: enhancement
