### ISSUE TITLE
interne Überprüfung fehlgeschlagen, internal check fails

### ISSUE THREAD

**Issue by LGv10AL** [M66B/XPrivacy#2353] opened 2016-06-02 09:49 UTC
Hi,

when i start xprivacy, an error message appears, "internal check fails".
If you need more informations, please tell me.

Here are my specs.
LG v10, rootet.
Android 5.1.1
Build LMY47V
SOftware-Version V10a-EUR-XX
Kernel 3.10.49

**Here is the logcat:**
[log.txt](https://github.com/M66B/XPrivacy/files/295288/log.txt)

**Here is the log, that xprivacy send per mai**l.

XPrivacy: 3.6.19
Android: 5.1.1 (SDK 22)

Brand: lge
Manufacturer: LGE
Model: LG-H960
Product: pplus_global_com
Device: pplus
Host: LGEACI5R6
Display: LMY47V
Id: LMY47V

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10868)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2557)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:585)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10868)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2557)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:585)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.onWakefulnessChanged(ActivityManagerService.java:10716)
at com.android.server.am.ActivityManagerService$LocalService.onWakefulnessChanged(ActivityManagerService.java:20937)
at com.android.server.power.Notifier$1.run(Notifier.java:294)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at com.android.server.SystemServer.run(SystemServer.java:283)
at com.android.server.SystemServer.main(SystemServer.java:184)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10868)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2557)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:585)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at android.os.Binder.execTransact(<Xposed>)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.onWakefulnessChanged(ActivityManagerService.java:10716)
at com.android.server.am.ActivityManagerService$LocalService.onWakefulnessChanged(ActivityManagerService.java:20937)
at com.android.server.power.Notifier$1.run(Notifier.java:294)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at com.android.server.SystemServer.run(SystemServer.java:283)
at com.android.server.SystemServer.main(SystemServer.java:184)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.onWakefulnessChanged(ActivityManagerService.java:10716)
at com.android.server.am.ActivityManagerService$LocalService.onWakefulnessChanged(ActivityManagerService.java:20937)
at com.android.server.power.Notifier$1.run(Notifier.java:294)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at com.android.server.SystemServer.run(SystemServer.java:283)
at com.android.server.SystemServer.main(SystemServer.java:184)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

java.lang.NoSuchFieldException: mSleeping uid=1000
java.lang.NoSuchFieldException: mSleeping
at java.lang.Class.getDeclaredField(Class.java:890)
at biz.bokhorst.xprivacy.XActivityManagerService.b(SourceFile:192)
at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.afterHookedMethod(SourceFile:660)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
at com.android.server.am.ActivityManagerService.updateSleepIfNeededLocked(<Xposed>)
at com.android.server.am.ActivityManagerService.setLockScreenShown(ActivityManagerService.java:10868)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at com.android.server.am.ActivityManagerService.setLockScreenShown(<Xposed>)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1336)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2557)
at com.android.server.am.ActivityManagerServiceEx.onTransact(ActivityManagerServiceEx.java:585)
at android.os.Binder.execTransact(Binder.java:446)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
at android.os.Binder.execTransact(<Xposed>)

**Comment by M66B** [comment] 2016-06-02 11:49
Duplicate of an existing issue

**Closed by M66B** 2016-06-02 11:49 UTC
Labels: bug, duplicate, lowprio
