### ISSUE TITLE
Not working on AOSP custom roms on lg g3

### ISSUE THREAD

**Issue by Halry** [M66B/XPrivacy#2152] opened 2015-02-28 11:35 UTC
Here is logcat:http://pastebin.com/ejvAexZX
I don't know whether it works on 4.4,because as soon I bought this phone,I flash it to lollipop.
Maybe is xposed problem.Greenify won't work,too.

**Comment by M66B** [comment] 2015-02-28 11:38
Duplicate of #2148

**Closed** 2015-02-28 11:38 UTC
Labels: duplicate
