### ISSUE TITLE
[Lollipop] Telephone number not restricted

### ISSUE THREAD

**Issue by bonanza123** [M66B/XPrivacy#2141] opened 2015-02-16 16:44 UTC
Hi,

for me it seems that telephone related data, e.g. phone number, carrier, etc is not being restricted. Similarly for me the "internet.connect" restriction does not apply ( I mean there is no request popup in "restrict on deman" mode and the app can connect to any website). All the data is also not shown as restricted or allowed in the Xprivacy log.

Here a hopefully helpful logcat: http://pastebin.com/9HVqKutc

P.s: I'm running CM12 on my nexus 5 (hammerhead) 

Edit: for testing I used this app: https://play.google.com/store/apps/details?id=aws.apps.networkInfoIi

**Comment by M66B** [comment] 2015-02-16 16:59
Can you please be more specific about which restriction do not seem to work?

At least a few restrictions in the same category seem to work:

```
02-16 17:32:29.051 I/XPrivacy(753): Get service 1000/getSimOperator(null;null) phone=!restricted? (mcached) 5 ms
02-16 17:33:39.959 I/XPrivacy(753): Get service 10076/Srv_getCellLocation(null;null) location=!restricted? (ccached) 4 ms
02-16 17:33:39.980 I/XPrivacy(753): Get service 10076/Srv_getNeighboringCellInfo(null;null) location=!restricted? (ccached) 1 ms
```

So, it would be strange if the others do not work.

Did you check the usage data?

**Comment by bonanza123** [comment] 2015-02-16 17:07
Thanks for your fast response! Definately not working is the restriction of the phone number ( Sorry I dont know the corresponding permission) Also none of the phone-category related stuff is shown in the Log ( neither as restricted nor at allowed, simply not listed at all )

**Comment by M66B** [comment] 2015-02-16 17:47
Another note: I will not work on fixing things for Lollipop until this issue has been solved:
http://forum.xda-developers.com/showpost.php?p=58861682&postcount=45

As long ad this issue is not solved, the project goal, providing a decent privacy solution for manu users, cannot be reached.

**Comment by gruez** [comment] 2015-03-09 05:25
I can confirm that phone number restriction doesn't work. Google Hangouts is still able to detect my original phone number after setting it to restrict on demand.

**Comment by M66B** [comment] 2015-03-09 06:20
@gruez can you please post a logcat with XPrivacy debug logging enabled?

**Comment by gruez** [comment] 2015-03-10 02:08
https://gist.github.com/gruez/d7fc992e73c3a54024e0

Before rebooting, I force stopped the app, cleared all of its data, and reset its restrictions on xprivacy (restrictions will be asked). After rebooting the phone, I opened the app and went to its settings menu, where it showed my phone number and asked me to confirm it. I answered "deny" to every xprivacy prompt execpt accounts.

Prior testing showed that clearing the data and removing the sim card will cause the app to show no phone number, which suggests the phone number is not cached.

**Comment by M66B** [comment] 2015-03-10 03:15
Which restriction caused the phone number to be faked/hidden before?

**Comment by M66B** [comment] 2015-03-13 06:39
Please try the version from here: #2162

**Comment by M66B** [comment] 2015-05-19 04:50
Will be fixed in the next release, but will result in bootloops in many cases, because of a bug in Xposed.

**Closed by M66B** 2015-05-19 04:50 UTC
Labels: bug, Lollipop, lowprio
