### ISSUE TITLE
Xprivacy menu

### ISSUE THREAD

**Issue by smiledexter** [M66B/XPrivacy#2186] opened 2015-05-05 08:06 UTC
menu is not working right, can not hide the window automatically https://youtu.be/z4t5TJCJ3PE
This issue is the last version, which was not previously.

**Comment by M66B** [comment] 2015-05-05 08:08
Probably a duplicate of #2182

**Comment by smiledexter** [comment] 2015-05-05 08:09
thanks

**Closed by M66B** 2015-05-05 08:08 UTC
