### ISSUE TITLE
Clicking on greyed out app in app list will load wrong app details

### ISSUE THREAD

**Issue by danielmmmm** [M66B/XPrivacy#2109] opened 2015-01-07 19:17 UTC
When a greyed out app (icon and restrictions not loaded yet) in the app list is clicked, XPrivacy will show the details of a different app. I suspect it will show the details of the app that is at the position of the clicked app in the list of already loaded apps in the memory (hard to describe).

Marcel, it would be very helpful if you could fix this because then one would not have to wait for the app list to be populated (app icon and restrictions).

I hope my description was not too confusing.

**Comment by M66B** [comment] 2015-01-08 18:49
I cannot reproduce this issue in the latest beta.
What do you exactly tap?
The application name? or its icon?

**Comment by danielmmmm** [comment] 2015-01-08 20:13
The app name, since the icon has not loaded yet. I tried clicking on the empty space where the icon will appear eventually, but nothing happened.

**Comment by M66B** [comment] 2015-01-08 20:29
This should be fixed in the latest beta version, see this commit: https://github.com/M66B/XPrivacy/commit/a683a48f7b289c7a5f01721eb2506d05bbb6e1fd

**Comment by danielmmmm** [comment] 2015-01-09 08:41
Did you already publish this beta? I have 3.5.10 (460) installed.

Also, does this change mean that we won't be able to click the name of an app before all details were loaded? That would be unfortunate because it would slow down user interaction tremendously.
To bad that there was a problem with memory with caching switched on ...

**Comment by M66B** [comment] 2015-01-09 08:52
This will be fixed in the next release.

**Closed** 2015-01-09 08:51 UTC
Labels: bug, lowprio

**Comment by danielmmmm** [comment] 2015-01-09 08:55
Meaning greyed out apps will be clickable or meaning that clicks won't do anything? ;-)

**Comment by M66B** [comment] 2015-01-09 08:57
Clicks won't do anything, since else the wrong application details will be opened.

**Comment by danielmmmm** [comment] 2015-01-09 10:36
Thanks a lot!
I hope you are satisfied with your (not so new any more) project and that XPrivacy doesn't keep you too busy!

**Comment by M66B** [comment] 2015-01-09 10:38
My new project is quite nice, thanks. Nevertheless I will keep my promise to maintain XPrivacy, meaning I will fix bugs and add new restrictions when requested.

Did you test 3.5.11 already? It should fix this issue.

**Comment by danielmmmm** [comment] 2015-01-09 10:59
Good to hear that you like your project!
And of course good to here (again) that you will continue to support us with XPrivacy!

3.5.11 works perfectly well! Now I (and maybe some other users?) don't have to care about missing caching any more. Thanks!

**Comment by Anusha-G-Rao** [comment] 2017-09-23 15:08
Hi, 
Was curious to know why some of the apps are greyed out. Could you please guide me to some documentation where I can find more about it. Thank you very much.

**Comment by M66B** [comment] 2017-09-23 15:59
Please read the support section here on GitHub to see how you can ask your questions.
